# Generated by Django 4.1.3 on 2022-11-05 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_appointment_course_registration_payment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={"ordering": ["last_name"]},),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("1", "nicht bezahlt"), ("2", "bezahlt")],
                default="1",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="backend.user",
            ),
        ),
    ]
